const String authScreenTagLine = 'The podcasting app that lets you vibe with your favorite creators';
const String appName = 'Vibe Podcasting';
const String CONFIG = 'configs';
const String firebaseUnsupportError = 'DefaultFirebaseOptions have not been configured for web - you can reconfigure this by running the FlutterFire CLI again.';
const String loginLabel = 'Login';
const String loginTagLine = 'Login to start vibing with your favorite creators';
const String registerLabel = 'Register';
const String registerTagLine = 'Create an account to start vibing with your favorite creators';
const String runGuardedError = 'runZonedGuarded: Caught error in my root zone.';
