import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData defaultDarkTheme = ThemeData(
  brightness: Brightness.dark,
  primaryColor: const Color(0xFFE6AA68),
  primaryColorLight: const Color(0xFFFA7C2E),
  primaryColorDark: const Color(0xFFFA7C2E),
  canvasColor: const Color(0x0ff090C08),
  scaffoldBackgroundColor: const Color(0x0ff090C08),
  cardColor: const Color(0x0ff090C08),
  dividerColor: const Color(0xFFBDBDBD),
  focusColor: const Color(0xFFFA7C2E),
  hoverColor: const Color(0xFFFA7C2E),
  highlightColor: const Color(0xFFFA7C2E),
  splashColor: const Color(0xFFFA7C2E),
  unselectedWidgetColor: const Color(0xFFFFFFFF),
  disabledColor: const Color(0xFFFA7C2E),
  secondaryHeaderColor: const Color(0xFFFA7C2E),
  textSelectionTheme: const TextSelectionThemeData(
    selectionColor: Color(0xFFFA7C2E),
    cursorColor: Color(0xFFFA7C2E),
    selectionHandleColor: Color(0xFFFA7C2E),
  ),
  dialogBackgroundColor: const Color(0x0ff090C08),
  indicatorColor: const Color(0xFFFA7C2E),
  hintColor: const Color(0xFFFA7C2E),
  toggleButtonsTheme: const ToggleButtonsThemeData(
    color: Color(0xFFFA7C2E),
    selectedColor: Color(0xFFFA7C2E),
    fillColor: Color(0xFFFA7C2E),
    focusColor: Color(0xFFFA7C2E),
    highlightColor: Color(0xFFFA7C2E),
    hoverColor: Color(0xFFFA7C2E),
    splashColor: Color(0xFFFA7C2E),
    borderColor: Color(0xFFFA7C2E),
    selectedBorderColor: Color(0xFFFA7C2E),
  ),
  colorScheme: const ColorScheme(
    primary: Color(0xFFFF8C42),
    secondary: Color(0xFFFA7C2E),
    surface: Color(0x0ff090C08),
    background: Color(0x0ff090C08),
    error: Color(0xFFA23E48),
    onPrimary: Color(0x0ff090C08),
    onSecondary: Color(0xFFFFFFFF),
    onSurface: Color(0xFFFFFFFF),
    onBackground: Color(0xFFFFFFFF),
    onError: Color(0x0ff090C08),
    brightness: Brightness.dark,
  ),
  textTheme: TextTheme(
    displayLarge: GoogleFonts.poppins(
      fontSize: 34,
      fontWeight: FontWeight.bold,
      color: const Color(0xFFFFFFFF),
    ),
    displayMedium: GoogleFonts.poppins(
      fontSize: 24,
      fontWeight: FontWeight.bold,
      color: const Color(0xFFFFFFFF),
    ),
    displaySmall:  GoogleFonts.poppins(
      fontSize: 18,
      fontWeight: FontWeight.bold,
      color: const Color(0xFFFFFFFF),
    ),
    bodyLarge:  GoogleFonts.poppins(
      fontSize: 16,
      fontWeight: FontWeight.normal,
      color: const Color(0xFFFFFFFF),
    ),
    bodyMedium: GoogleFonts.poppins(
      fontSize: 14,
      fontWeight: FontWeight.normal,
      color: const Color(0xFFFFFFFF),
    ),
    bodySmall: GoogleFonts.poppins(
      fontSize: 12,
      fontWeight: FontWeight.normal,
      color: const Color(0xFFFFFFFF),
    ),
  ),
);