# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/java@v2
        with:
            distribution: 'zulu'
            java-version: '11'
        env:
            GOOGLE_SERVICES_JSON: ${{ secrets.debug.GOOGLE_SERVICES_JSON }}
            PR_NUMBER_AND_MESSAGE: ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
            FIREBASE_OPTIONS: ${{ secrets.debug.FIREBASE_OPTIONS }}
            FIREBASE_APP_ID_ANDROID: ${{ secrets.debug.FIREBASE_APP_ID_ANDROID }}
            FIREBASE_APP_ID_IOS: ${{ secrets.debug.FIREBASE_APP_ID_IOS }}
            FIREBASE_TOKEN: ${{ secrets.debug.FIREBASE_TOKEN }}

        run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

      - name: Set Up Firebase
        run: echo "$FIREBASE_OPTIONS" > app/lib/firebase_options.dart

        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor
      - run: flutter pub get

      - name: Run Tests
        run: flutter test


      - name: Create Android Artifact
        run: flutter build apk --debug

      - name: Create iOS Artifact
        run: flutter build ios --debug

      - name: Upload Android Artifact
        uses: hasretsariyer/firebase-app-distribution-action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          app_file: build/app/outputs/flutter-apk/app-debug.apk
          release_notes: ${{ env.PR_NUMBER_AND_MESSAGE }}

      - name: Upload iOS Artifact
        uses: hasretsariyer/firebase-app-distribution-action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          app_file: build/ios/iphoneos/Runner.app
          release_notes: ${{ env.PR_NUMBER_AND_MESSAGE }}
