# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]

permissions: write-all

jobs:

  upload_to_firebase:
    name: Upload Android Artifact
    runs-on: macos-latest
    env:
      PR_NUMBER_AND_MESSAGE: ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}
      FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
            - uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
              with:
                appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
                token: ${{ secrets.FIREBASE_TOKEN }}
                file: build/app/outputs/flutter-apk/app-debug.apk
                releaseNotes: ${{ env.PR_NUMBER_AND_MESSAGE }}
            - uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
              with:
                appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
                token: ${{ secrets.FIREBASE_TOKEN }}
                file: build/ios/iphoneos/Runner.app
                releaseNotes: ${{ env.PR_NUMBER_AND_MESSAGE }}

  finalize:
        name: Finalize
        needs: [ upload_android, upload_ios ]
        runs-on: ubuntu-latest
        steps:
          - name: Finalize
            run: echo "Finalized"